# Generated by Django 5.2.16 on 2026-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_manufacturer',
            field=models.CharField(blank=True, help_text='Spare Parts only — the vehicle maker this part fits (e.g. Maruti, Honda).', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Spare Parts only — the vehicle model this part fits (e.g. Swift, Activa).', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(help_text='Manufacturer / brand of the tool or part.', max_length=150),
        ),
    ]
